export enum SportTypes {
Canoeing = "Canoeing",
Kayaking = "Kayaking",
Sailing = "Sailing",
Canyoneering = "Canyoneering",
Paragliding = "Paragliding",
AdventureRacing = "Adventure Racing",
GravelCycling = "Gravel Cycling",
RoadCycling = "Road Cycling",
MountainBiking = "Mountain Biking",
Skiing = "Skiing",
Snowboarding = "Snowboarding",
Snowshoeing = "Snowshoeing",
SkiMountaineering = "Ski Mountaineering",
TrailRunning = "Trail Running",
Hiking = "Hiking",
Backpacking = "Backpacking",
UltralightBackpacking = "Ultralight Backpacking",
Camping = "Camping",
Geocaching = "Geocaching",
Orienteering = "Orienteering",
Birdwatching = "Birdwatching",
Mountaineering = "Mountaineering",
RockClimbing = "Rock Climbing",
HorsebackRiding = "Horseback Riding",
Other = "Other"
}